### ISSUE TITLE
Doesn't require `transform-object-rest-spread`

### ISSUE THREAD

**Issue by jmm** [thejameskyle/react-stylish#1]
> I~~f you are using the ES7 object spread operator i~~t's as simple as this:

`JSXSpreadAttribute` is part of JSX and doesn't require `babel-plugin-transform-object-rest-spread` :tada:

**Comment by thejameskyle** [comment]
Oh really? So we compile it down completely in the react preset?

**Comment by jmm** [comment]
Yessir, `babel-plugin-transform-react-jsx` (and therefore the preset of course). Though they're obviously closely related, `JSXSpreadAttribute` is its own thing defined in JSX* and even under the covers the implementation in Babel is all under the umbrella of JSX and not related to object spread I believe.

*I don't know what will happen if object spread doesn't get standardized.

You can do a minimal repro like this:

```js
babel.transform('<X {...props} attr />', {
  plugins: ["transform-react-jsx"],
});
```

Object spread handling goes down here: https://github.com/babel/babel/blob/12b7a44796a504dbe5841473b899e499cae30749/packages/babylon/src/parser/expression.js#L687

While JSX spread is here:

https://github.com/babel/babel/blob/12b7a44796a504dbe5841473b899e499cae30749/packages/babylon/src/plugins/jsx/index.js#L285-L290

https://github.com/babel/babel/blob/12b7a44796a504dbe5841473b899e499cae30749/packages/babel-helper-builder-react-jsx/src/index.js#L157

**Comment by thejameskyle** [comment]
updated readme
